import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>My App</title>
      </head>
      <body>
        <div className="flex flex-row justify-between items-center p-4">
          <div className="left-links">
            <Link href="/"></Link>
            <Link href="/">Blogs</Link>
          </div>
          <div className="right-links">
            <Link href="/admin"></Link>
          </div>
        </div>
        <main className="max-w-3xl mx-auto px-4 sm:px-6 py-16">{children}</main>
      </body>
    </html>
  );
}
